DROP TABLE BASEBALL_ANALYSIS.SALARY_ASSET_STAGE ;
CREATE TABLE BASEBALL_ANALYSIS.SALARY_ASSET_STAGE  
WITH SALARY_DATA AS (
SELECT
PLAYERID
,S.YEARID
,S.TEAMID
,S.SALARY
,ROW_NUMBER () OVER (PARTITION BY PLAYERID ORDER BY S.YEARID ASC) AS YEAR_RNK
FROM BASEBALL_STATS.SALARIES S
)
,PLAYER_DATA AS (
SELECT 
PI.PLAYERID
,YEAR(DEBUT) AS DEBUT_YEAR
,YEAR(FINALGAME) AS FINAL_YEAR
,YEAR(FINALGAME)-YEAR(DEBUT) AS YEARS_PLAYED
,S.YEARID AS SEASON_YEAR
,S.YEARID - DEBUT AS YEAR_OF_CAREER
,S.TEAMID
,S.SALARY
,CASE WHEN S.YEAR_RNK =1 THEN 0 ELSE S2.SALARY END AS SALARY_MINUS_1
FROM BASEBALL_STATS.PLAYER_INFO PI
LEFT JOIN SALARY_DATA S
ON PI.PLAYERID = S.PLAYERID 
LEFT JOIN SALARY_DATA S2
ON S2.PLAYERID = S.PLAYERID
AND  S2.YEAR_RNK+1 = S.YEAR_RNK
WHERE YEAR(DEBUT) >=1990
AND S.YEARID IS NOT NULL
#AND PI.PLAYERID = 'podsesc01'
)
, BATTING_DATA AS (
SELECT
B.PLAYERID
,SEASON_YEAR
,YEAR_OF_CAREER
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-1 THEN AB ELSE 0 END) AS B_AB_MINUS_1
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-2 THEN AB ELSE 0 END) AS B_AB_MINUS_2
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-3 THEN AB ELSE 0 END) AS B_AB_MINUS_3
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-1 THEN R ELSE 0 END) AS B_RUNS_MINUS_1
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-2 THEN R ELSE 0 END) AS B_RUNS_MINUS_2
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-3 THEN R ELSE 0 END) AS B_RUNS_MINUS_3
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-1 THEN H ELSE 0 END) AS B_HITS_MINUS_1
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-2 THEN H ELSE 0 END) AS B_HITS_MINUS_2
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-3 THEN H ELSE 0 END) AS B_HITS_MINUS_3
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-1 THEN HR ELSE 0 END) AS B_HR_MINUS_1
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-2 THEN HR ELSE 0 END) AS B_HR_MINUS_2
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-3 THEN HR ELSE 0 END) AS B_HR_MINUS_3
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-1 THEN BB ELSE 0 END) AS B_BB_MINUS_1
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-2 THEN BB ELSE 0 END) AS B_BB_MINUS_2
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-3 THEN BB ELSE 0 END) AS B_BB_MINUS_3
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-1 THEN SO ELSE 0 END) AS B_SO_MINUS_1
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-2 THEN SO ELSE 0 END) AS B_SO_MINUS_2
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-3 THEN SO ELSE 0 END) AS B_SO_MINUS_3
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-1 THEN SB ELSE 0 END) AS B_SB_MINUS_1
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-2 THEN SB ELSE 0 END) AS B_SB_MINUS_2
,SUM(CASE WHEN B.YEARID=SEASON_YEAR-3 THEN SB ELSE 0 END) AS B_SB_MINUS_3

FROM PLAYER_DATA PI
INNER JOIN BASEBALL_STATS.BATTING B
ON PI.PLAYERID = B.PLAYERID
AND B.YEARID BETWEEN SEASON_YEAR-3 AND SEASON_YEAR-1
GROUP BY 1,2,3
)
, PITCHING_DATA AS (
SELECT
P.PLAYERID
,SEASON_YEAR
,YEAR_OF_CAREER
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-1 THEN IPOuts ELSE 0 END) AS P_INNOUTS_MINUS_1
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-2 THEN IPOuts ELSE 0 END) AS P_INNOUTS_MINUS_2
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-3 THEN IPOuts ELSE 0 END) AS P_INNOUTS_MINUS_3
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-1 THEN GS ELSE 0 END) AS P_GS_MINUS_1
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-2 THEN GS ELSE 0 END) AS P_GS_MINUS_2
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-3 THEN GS ELSE 0 END) AS P_GS_MINUS_3
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-1 THEN CG ELSE 0 END) AS P_CG_MINUS_1
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-2 THEN CG ELSE 0 END) AS P_CG_MINUS_2
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-3 THEN CG ELSE 0 END) AS P_CG_MINUS_3
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-1 THEN SV ELSE 0 END) AS P_SAVES_MINUS_1
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-2 THEN SV ELSE 0 END) AS P_SAVES_MINUS_2
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-3 THEN SV ELSE 0 END) AS P_SAVES_MINUS_3
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-1 THEN H ELSE 0 END) AS P_HITS_MINUS_1
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-2 THEN H ELSE 0 END) AS P_HITS_MINUS_2
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-3 THEN H ELSE 0 END) AS P_HITS_MINUS_3
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-1 THEN ER ELSE 0 END) AS P_ER_MINUS_1
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-2 THEN ER ELSE 0 END) AS P_ER_MINUS_2
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-3 THEN ER ELSE 0 END) AS P_ER_MINUS_3
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-1 THEN HR ELSE 0 END) AS P_HR_MINUS_1
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-2 THEN HR ELSE 0 END) AS P_HR_MINUS_2
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-3 THEN HR ELSE 0 END) AS P_HR_MINUS_3
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-1 THEN BB ELSE 0 END) AS P_BB_MINUS_1
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-2 THEN BB ELSE 0 END) AS P_BB_MINUS_2
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-3 THEN BB ELSE 0 END) AS P_BB_MINUS_3
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-1 THEN SO ELSE 0 END) AS P_SO_MINUS_1
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-2 THEN SO ELSE 0 END) AS P_SO_MINUS_2
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-3 THEN SO ELSE 0 END) AS P_SO_MINUS_3
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-1 THEN R ELSE 0 END) AS P_RUNS_MINUS_1
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-2 THEN R ELSE 0 END) AS P_RUNS_MINUS_2
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-3 THEN R ELSE 0 END) AS P_RUNS_MINUS_3
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-1 THEN BFP ELSE 0 END) AS P_BFP_MINUS_1
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-2 THEN BFP ELSE 0 END) AS P_BFP_MINUS_2
,SUM(CASE WHEN P.YEARID=SEASON_YEAR-3 THEN BFP ELSE 0 END) AS P_BFP_MINUS_3

FROM PLAYER_DATA PI
INNER JOIN BASEBALL_STATS.PITCHING P
ON PI.PLAYERID = P.PLAYERID
AND P.YEARID BETWEEN SEASON_YEAR-3 AND SEASON_YEAR-1
GROUP BY 1,2,3
)
,FIELDING_DATA AS (
SELECT
F.PLAYERID
,SEASON_YEAR
,YEAR_OF_CAREER
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-1 THEN InnOuts ELSE 0 END) AS F_INNOUTS_MINUS_1
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-2 THEN InnOuts ELSE 0 END) AS F_INNOUTS_MINUS_2
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-3 THEN InnOuts ELSE 0 END) AS F_INNOUTS_MINUS_3
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-1 THEN GS ELSE 0 END) AS F_GS_MINUS_1
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-2 THEN GS ELSE 0 END) AS F_GS_MINUS_2
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-3 THEN GS ELSE 0 END) AS F_GS_MINUS_3
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-1 THEN E ELSE 0 END) AS F_E_MINUS_1
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-2 THEN E ELSE 0 END) AS F_E_MINUS_2
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-3 THEN E ELSE 0 END) AS F_E_MINUS_3
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-1 THEN PB ELSE 0 END) AS F_PB_MINUS_1
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-2 THEN PB ELSE 0 END) AS F_PB_MINUS_2
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-3 THEN PB ELSE 0 END) AS F_PB_MINUS_3
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-1 THEN SB ELSE 0 END) AS F_SB_MINUS_1
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-2 THEN SB ELSE 0 END) AS F_SB_MINUS_2
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-3 THEN SB ELSE 0 END) AS F_SB_MINUS_3
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-1 THEN PO ELSE 0 END) AS F_PO_MINUS_1
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-2 THEN PO ELSE 0 END) AS F_PO_MINUS_2
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-3 THEN PO ELSE 0 END) AS F_PO_MINUS_3
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-1 THEN A ELSE 0 END) AS F_A_MINUS_1
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-2 THEN A ELSE 0 END) AS F_A_MINUS_2
,SUM(CASE WHEN F.YEARID=SEASON_YEAR-3 THEN A ELSE 0 END) AS F_A_MINUS_3

FROM PLAYER_DATA PI
INNER JOIN BASEBALL_STATS.FIELDING F
ON PI.PLAYERID = F.PLAYERID
AND F.YEARID BETWEEN SEASON_YEAR-3 AND SEASON_YEAR-1
GROUP BY 1,2,3
)
,ALLSTAR_DATA AS (
SELECT
A.PLAYERID
,SEASON_YEAR
,YEAR_OF_CAREER
,'Y' AS ALLSTAR_IND
,CASE WHEN startingPos <>0 THEN 'Y' ELSE 'N' END AS STARTED_ALLSTAR_IND
FROM PLAYER_DATA PI
INNER JOIN BASEBALL_STATS.ALLSTAR_FULL A
ON PI.PLAYERID = A.PLAYERID
AND A.YEARID BETWEEN SEASON_YEAR-3 AND SEASON_YEAR-1
GROUP BY 1,2,3,4,5
)
,AWARDS_DATA AS (
SELECT 
A.PLAYERID
,SEASON_YEAR
,YEAR_OF_CAREER
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-1 AND AWARDID = 'Cy Young' THEN pointsWon ELSE 0 END) AS A_CY_V_MINUS_1
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-2 AND AWARDID = 'Cy Young' THEN pointsWon ELSE 0 END) AS A_CY_V_MINUS_2
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-3 AND AWARDID = 'Cy Young' THEN pointsWon ELSE 0 END) AS A_CY_V_MINUS_3
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-1 AND AWARDID = 'Cy Young' THEN pointsMax ELSE 0 END) AS A_CY_MV_MINUS_1
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-2 AND AWARDID = 'Cy Young' THEN pointsMax ELSE 0 END) AS A_CY_MV_MINUS_2
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-3 AND AWARDID = 'Cy Young' THEN pointsMax ELSE 0 END) AS A_CY_MV_MINUS_3
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-1 AND AWARDID = 'MVP' THEN pointsWon ELSE 0 END) AS A_MVP_V_MINUS_1
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-2 AND AWARDID = 'MVP' THEN pointsWon ELSE 0 END) AS A_MVP_V_MINUS_2
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-3 AND AWARDID = 'MVP' THEN pointsWon ELSE 0 END) AS A_MVP_V_MINUS_3
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-1 AND AWARDID = 'MVP' THEN pointsMax ELSE 0 END) AS A_MVP_MV_MINUS_1
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-2 AND AWARDID = 'MVP' THEN pointsMax ELSE 0 END) AS A_MVP_MV_MINUS_2
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-3 AND AWARDID = 'MVP' THEN pointsMax ELSE 0 END) AS A_MVP_MV_MINUS_3
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-1 AND AWARDID = 'Rookie of the Year' THEN pointsWon ELSE 0 END) AS A_ROY_V_MINUS_1
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-2 AND AWARDID = 'Rookie of the Year' THEN pointsWon ELSE 0 END) AS A_ROY_V_MINUS_2
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-3 AND AWARDID = 'Rookie of the Year' THEN pointsWon ELSE 0 END) AS A_ROY_V_MINUS_3
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-1 AND AWARDID = 'Rookie of the Year' THEN pointsMax ELSE 0 END) AS A_ROY_MV_MINUS_1
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-2 AND AWARDID = 'Rookie of the Year' THEN pointsMax ELSE 0 END) AS A_ROY_MV_MINUS_2
,SUM(CASE WHEN A.YEARID=SEASON_YEAR-3 AND AWARDID = 'Rookie of the Year' THEN pointsMax ELSE 0 END) AS A_ROY_MV_MINUS_3
FROM PLAYER_DATA PI
INNER JOIN BASEBALL_STATS.AWARDS_SHARE_PLAYERS A
ON PI.PLAYERID = A.PLAYERID
AND A.YEARID BETWEEN SEASON_YEAR-3 AND SEASON_YEAR-1
GROUP BY 1,2,3
)
,CONTRACT_DATA AS (
SELECT FACT.*
FROM(
SELECT 
COALESCE(PI.PLAYERID,PI2.PLAYERID,PI3.PLAYERID) AS PLAYERID
,YEAR
,TEAM
,TYPE
,ROW_NUMBER () OVER (PARTITION BY C.LAST_NAME,C.FIRST_NAME,YEAR ORDER BY PI.PLAYERID, PI2.PLAYERID,PI3.PLAYERID) AS RNK
FROM BASEBALL_STATS.CONTRACTS C

LEFT JOIN BASEBALL_STATS.PLAYER_INFO PI
ON REPLACE(C.LAST_NAME,'⇑','') = PI.nameLast
AND REPLACE(C.FIRST_NAME,'⇑','') = REPLACE(PI.NAMEFIRST,' ','')

LEFT JOIN BASEBALL_STATS.PLAYER_INFO PI2
ON REPLACE(C.LAST_NAME,'⇑','') = PI2.nameLast
AND REPLACE(C.FIRST_NAME,'⇑','') = REPLACE(PI2.NAMEGIVEN,' ','')

LEFT JOIN BASEBALL_STATS.PLAYER_INFO PI3
ON CONCAT(SUBSTR(REPLACE(C.LAST_NAME,'⇑',''),1,5),LEFT(C.FIRST_NAME,2),'01')  = PI3.PLAYERID

WHERE COALESCE(PI.PLAYERID,PI2.PLAYERID,PI3.PLAYERID) IS NOT NULL
)FACT
WHERE RNK=1
)
,POSITION AS (
SELECT *
FROM(
SELECT
PI.PLAYERID
,PI.SEASON_YEAR
,PI.YEAR_OF_CAREER
,POS AS POSITION
,ROW_NUMBER() OVER (PARTITION BY PI.PLAYERID,PI.SEASON_YEAR ORDER BY InnOuts DESC) AS RNK

FROM PLAYER_DATA PI
INNER JOIN BASEBALL_STATS.FIELDING F
ON PI.PLAYERID = F.PLAYERID
AND F.YEARID = SEASON_YEAR
)FACT
WHERE RNK=1
)
SELECT
PI.PLAYERID
,PI.SEASON_YEAR
,PI.YEAR_OF_CAREER
,POS.POSITION
,PI.TEAMID
,PI.SALARY
,PI.SALARY_MINUS_1
,COALESCE(CD.TYPE,'NA') AS CONTRACT_TYPE
,COALESCE(A.ALLSTAR_IND,'N') AS ALLSTAR_IND
,COALESCE(A.STARTED_ALLSTAR_IND,'N') AS STARTED_ALLSTAR_IND
,COALESCE(B_AB_MINUS_1,0) AS B_AB_MINUS_1
,COALESCE(B_AB_MINUS_2,0) AS B_AB_MINUS_2
,COALESCE(B_AB_MINUS_3,0) AS B_AB_MINUS_3
,COALESCE(B_RUNS_MINUS_1,0) AS B_RUNS_MINUS_1
,COALESCE(B_RUNS_MINUS_2,0) AS B_RUNS_MINUS_2
,COALESCE(B_RUNS_MINUS_3,0) AS B_RUNS_MINUS_3
,COALESCE(B_HITS_MINUS_1,0) AS B_HITS_MINUS_1
,COALESCE(B_HITS_MINUS_2,0) AS B_HITS_MINUS_2
,COALESCE(B_HITS_MINUS_3,0) AS B_HITS_MINUS_3
,COALESCE(B_HR_MINUS_1,0) AS B_HR_MINUS_1
,COALESCE(B_HR_MINUS_2,0) AS B_HR_MINUS_2
,COALESCE(B_HR_MINUS_3,0) AS B_HR_MINUS_3
,COALESCE(B_BB_MINUS_1,0) AS B_BB_MINUS_1
,COALESCE(B_BB_MINUS_2,0) AS B_BB_MINUS_2
,COALESCE(B_BB_MINUS_3,0) AS B_BB_MINUS_3
,COALESCE(B_SO_MINUS_1,0) AS B_SO_MINUS_1
,COALESCE(B_SO_MINUS_2,0) AS B_SO_MINUS_2
,COALESCE(B_SO_MINUS_3,0) AS B_SO_MINUS_3
,COALESCE(B_SB_MINUS_1,0) AS B_SB_MINUS_1
,COALESCE(B_SB_MINUS_2,0) AS B_SB_MINUS_2
,COALESCE(B_SB_MINUS_3,0) AS B_SB_MINUS_3
,COALESCE(P_INNOUTS_MINUS_1,0) AS P_INNOUTS_MINUS_1
,COALESCE(P_INNOUTS_MINUS_2,0) AS P_INNOUTS_MINUS_2
,COALESCE(P_INNOUTS_MINUS_3,0) AS P_INNOUTS_MINUS_3
,COALESCE(P_GS_MINUS_1,0) AS P_GS_MINUS_1
,COALESCE(P_GS_MINUS_2,0) AS P_GS_MINUS_2
,COALESCE(P_GS_MINUS_3,0) AS P_GS_MINUS_3
,COALESCE(P_CG_MINUS_1,0) AS P_CG_MINUS_1
,COALESCE(P_CG_MINUS_2,0) AS P_CG_MINUS_2
,COALESCE(P_CG_MINUS_3,0) AS P_CG_MINUS_3
,COALESCE(P_SAVES_MINUS_1,0) AS P_SAVES_MINUS_1
,COALESCE(P_SAVES_MINUS_2,0) AS P_SAVES_MINUS_2
,COALESCE(P_SAVES_MINUS_3,0) AS P_SAVES_MINUS_3
,COALESCE(P_HITS_MINUS_1,0) AS P_HITS_MINUS_1
,COALESCE(P_HITS_MINUS_2,0) AS P_HITS_MINUS_2
,COALESCE(P_HITS_MINUS_3,0) AS P_HITS_MINUS_3
,COALESCE(P_ER_MINUS_1,0) AS P_ER_MINUS_1
,COALESCE(P_ER_MINUS_2,0) AS P_ER_MINUS_2
,COALESCE(P_ER_MINUS_3,0) AS P_ER_MINUS_3
,COALESCE(P_HR_MINUS_1,0) AS P_HR_MINUS_1
,COALESCE(P_HR_MINUS_2,0) AS P_HR_MINUS_2
,COALESCE(P_HR_MINUS_3,0) AS P_HR_MINUS_3
,COALESCE(P_BB_MINUS_1,0) AS P_BB_MINUS_1
,COALESCE(P_BB_MINUS_2,0) AS P_BB_MINUS_2
,COALESCE(P_BB_MINUS_3,0) AS P_BB_MINUS_3
,COALESCE(P_SO_MINUS_1,0) AS P_SO_MINUS_1
,COALESCE(P_SO_MINUS_2,0) AS P_SO_MINUS_2
,COALESCE(P_SO_MINUS_3,0) AS P_SO_MINUS_3
,COALESCE(P_RUNS_MINUS_1,0) AS P_RUNS_MINUS_1
,COALESCE(P_RUNS_MINUS_2,0) AS P_RUNS_MINUS_2
,COALESCE(P_RUNS_MINUS_3,0) AS P_RUNS_MINUS_3
,COALESCE(P_BFP_MINUS_1,0) AS P_BFP_MINUS_1
,COALESCE(P_BFP_MINUS_2,0) AS P_BFP_MINUS_2
,COALESCE(P_BFP_MINUS_3,0) AS P_BFP_MINUS_3
,COALESCE(F_INNOUTS_MINUS_1,0) AS F_INNOUTS_MINUS_1
,COALESCE(F_INNOUTS_MINUS_2,0) AS F_INNOUTS_MINUS_2
,COALESCE(F_INNOUTS_MINUS_3,0) AS F_INNOUTS_MINUS_3
,COALESCE(F_GS_MINUS_1,0) AS F_GS_MINUS_1
,COALESCE(F_GS_MINUS_2,0) AS F_GS_MINUS_2
,COALESCE(F_GS_MINUS_3,0) AS F_GS_MINUS_3
,COALESCE(F_E_MINUS_1,0) AS F_E_MINUS_1
,COALESCE(F_E_MINUS_2,0) AS F_E_MINUS_2
,COALESCE(F_E_MINUS_3,0) AS F_E_MINUS_3
,COALESCE(F_PB_MINUS_1,0) AS F_PB_MINUS_1
,COALESCE(F_PB_MINUS_2,0) AS F_PB_MINUS_2
,COALESCE(F_PB_MINUS_3,0) AS F_PB_MINUS_3
,COALESCE(F_SB_MINUS_1,0) AS F_SB_MINUS_1
,COALESCE(F_SB_MINUS_2,0) AS F_SB_MINUS_2
,COALESCE(F_SB_MINUS_3,0) AS F_SB_MINUS_3
,COALESCE(F_PO_MINUS_1,0) AS F_PO_MINUS_1
,COALESCE(F_PO_MINUS_2,0) AS F_PO_MINUS_2
,COALESCE(F_PO_MINUS_3,0) AS F_PO_MINUS_3
,COALESCE(F_A_MINUS_1,0) AS F_A_MINUS_1
,COALESCE(F_A_MINUS_2,0) AS F_A_MINUS_2
,COALESCE(F_A_MINUS_3,0) AS F_A_MINUS_3
,COALESCE(A_CY_V_MINUS_1,0) AS A_CY_V_MINUS_1
,COALESCE(A_CY_V_MINUS_2,0) AS A_CY_V_MINUS_2
,COALESCE(A_CY_V_MINUS_3,0) AS A_CY_V_MINUS_3
,COALESCE(A_CY_MV_MINUS_1,0) AS A_CY_MV_MINUS_1
,COALESCE(A_CY_MV_MINUS_2,0) AS A_CY_MV_MINUS_2
,COALESCE(A_CY_MV_MINUS_3,0) AS A_CY_MV_MINUS_3
,COALESCE(A_MVP_V_MINUS_1,0) AS A_MVP_V_MINUS_1
,COALESCE(A_MVP_V_MINUS_2,0) AS A_MVP_V_MINUS_2
,COALESCE(A_MVP_V_MINUS_3,0) AS A_MVP_V_MINUS_3
,COALESCE(A_MVP_MV_MINUS_1,0) AS A_MVP_MV_MINUS_1
,COALESCE(A_MVP_MV_MINUS_2,0) AS A_MVP_MV_MINUS_2
,COALESCE(A_MVP_MV_MINUS_3,0) AS A_MVP_MV_MINUS_3
,COALESCE(A_ROY_V_MINUS_1,0) AS A_ROY_V_MINUS_1
,COALESCE(A_ROY_V_MINUS_2,0) AS A_ROY_V_MINUS_2
,COALESCE(A_ROY_V_MINUS_3,0) AS A_ROY_V_MINUS_3
,COALESCE(A_ROY_MV_MINUS_1,0) AS A_ROY_MV_MINUS_1
,COALESCE(A_ROY_MV_MINUS_2,0) AS A_ROY_MV_MINUS_2
,COALESCE(A_ROY_MV_MINUS_3,0) AS A_ROY_MV_MINUS_3

FROM PLAYER_DATA PI
LEFT JOIN BATTING_DATA B
ON PI.PLAYERID = B.PLAYERID
AND PI.SEASON_YEAR=B.SEASON_YEAR
LEFT JOIN PITCHING_DATA P
ON PI.PLAYERID = P.PLAYERID
AND PI.SEASON_YEAR=P.SEASON_YEAR
LEFT JOIN FIELDING_DATA F
ON PI.PLAYERID = F.PLAYERID
AND PI.SEASON_YEAR=F.SEASON_YEAR
LEFT JOIN ALLSTAR_DATA A
ON PI.PLAYERID = A.PLAYERID
AND PI.SEASON_YEAR=A.SEASON_YEAR
LEFT JOIN AWARDS_DATA AW
ON PI.PLAYERID = AW.PLAYERID
AND PI.SEASON_YEAR=AW.SEASON_YEAR
LEFT JOIN CONTRACT_DATA CD
ON PI.PLAYERID = CD.PLAYERID
AND PI.SEASON_YEAR=CD.YEAR
LEFT JOIN POSITION POS
ON PI.PLAYERID = POS.PLAYERID
AND PI.SEASON_YEAR=POS.SEASON_YEAR
;


SELECT *
FROM BASEBALL_ANALYSIS.SALARY_ASSET_STAGE  
WHERE PLAYERID = 'podsesc01'
ORDER BY SEASON_YEAR

SELECT *
FROM BASEBALL_STATS.SALARIES
WHERE PLAYERID = 'podsesc01'

SELECT * FROM BASEBALL_STATS.PLAYER_INFO 
WHERE PLAYERID = 'podsesc01'




wohlema01
bootyjo01

