#CREATE DATABASE BASEBALL_STATS;
USE BASEBALL_STATS;

TRUNCATE TABLE ALLSTAR_FULL;
TRUNCATE TABLE APPEARANCES;
TRUNCATE TABLE AWARDS_MANAGERS;
TRUNCATE TABLE AWARDS_PLAYERS;
TRUNCATE TABLE AWARDS_SHARE_PLAYERS;
TRUNCATE TABLE AWARDS_SHARE_MANAGERS;
TRUNCATE TABLE BATTING;
TRUNCATE TABLE BATTING_POST;
TRUNCATE TABLE COLLEGE_PLAYING;
TRUNCATE TABLE FIELDING;
TRUNCATE TABLE FIELDING_OF;
TRUNCATE TABLE FIELDING_OF_SPLIT;
TRUNCATE TABLE FIELDING_POST;
TRUNCATE TABLE HALL_OF_FAME;
TRUNCATE TABLE HOME_GAMES;
TRUNCATE TABLE MANAGERS;
TRUNCATE TABLE PARKS;
TRUNCATE TABLE PITCHING;
TRUNCATE TABLE PITCHING_POST;
TRUNCATE TABLE PLAYER_INFO;
TRUNCATE TABLE SALARIES;
TRUNCATE TABLE SERIES_POST;
TRUNCATE TABLE TEAMS;


LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/AllstarFull.csv"
INTO TABLE ALLSTAR_FULL
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/Appearances.csv"
INTO TABLE APPEARANCES
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/AwardsPlayers.csv"
INTO TABLE AWARDS_PLAYERS
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/AwardsManagers.csv"
INTO TABLE AWARDS_MANAGERS
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/AwardsSharePlayers.csv"
INTO TABLE AWARDS_SHARE_PLAYERS
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/AwardsShareManagers.csv"
INTO TABLE AWARDS_SHARE_MANAGERS
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/Batting.csv"
INTO TABLE BATTING
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/BattingPost.csv"
INTO TABLE BATTING_POST
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/CollegePlaying.csv"
INTO TABLE COLLEGE_PLAYING
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/Fielding.csv"
INTO TABLE FIELDING
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/FieldingOF.csv"
INTO TABLE FIELDING_OF
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/FieldingPost.csv"
INTO TABLE FIELDING_POST
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/FieldingOFsplit.csv"
INTO TABLE FIELDING_OF_SPLIT
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/HallOfFame.csv"
INTO TABLE HALL_OF_FAME
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/HomeGames.csv"
INTO TABLE HOME_GAMES
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/Managers.csv"
INTO TABLE MANAGERS
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/Parks.csv"
INTO TABLE PARKS
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/Pitching.csv"
INTO TABLE PITCHING
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/PitchingPost.csv"
INTO TABLE PITCHING_POST
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/Master.csv"
INTO TABLE PLAYER_INFO
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/Salaries.csv"
INTO TABLE SALARIES
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/SeriesPost.csv"
INTO TABLE SERIES_POST
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;
LOAD DATA LOCAL INFILE "c:/users/fbpol/documents/ml_projects/baseball/Teams.csv"
INTO TABLE TEAMS
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;